---
- hosts: all
  sudo: yes         
  tasks:
    - name: Generate key for root
      user: name=root generate_ssh_key=yes
      
    - name: Set password for root user (needed for MapR Web UI login)
      user: name=root password=$root_password_hash
  
    - include: configure_mapr.yml
        
    - name: Wait for MapR CLDB to be available
      wait_for: port=7222 delay=5 timeout=600 # wait up to 10 minutes
    
    - name: Wait for MapR web UI to be available
      wait_for: port=8443 delay=5 timeout=600 # wait up to 10 minutes
    
    # These hacks needed because I can't get the darn quotation escaping right to call them remotely
    # Must be done after CLDB is up (blocking for web ui is a nice way to wait for this)      
    - name: maprcli ganglia hack 1
      command: maprcli config save -values '{"cldb.ganglia.cldb.metrics":"1"}' 
      ignore_errors: yes
    - name: maprcli ganglia hack 2
      command: maprcli config save -values '{"cldb.ganglia.fileserver.metrics":"1"}'
      ignore_errors: yes
    - name: maprcli ganglia hack 3
      command:  maprcli config save -values "{\"cldb.default.volume.topology\":\"/data\"}"
      ignore_errors: yes
      
    - name: Setup MapR root user
      command:  maprcli acl edit -type cluster -user root:fc
        
    - name: install ganglia config
      template: src=gmetad.conf.j2 dest=/etc/ganglia/gmetad.conf owner=root group=root
    
    - name: Restart ganglia service
      service: name=ganglia-monitor state=restarted pattern=ganglia-monitor  # pattern needed since the init script doesn't support status option
      
    - name: Restart ganglia gmetad  
      service: name=gmetad state=restarted pattern=gmetad # pattern needed since the init script doesn't support status option
         
    - name: Restart apache
      service: name=apache2 state=restarted  
     
      
    